<?php if ( !defined('ABSPATH') ) exit('No direct script access allowed');
/**
 * theme/custom-styles.php
 * ============================================ *
 */
?>
<?php
add_action('wp_head', 'pure_assets');

if ( !function_exists( 'pure_assets' ) ) {
function pure_assets() 
{
global $pure_selectors;
$pure_selectors = array();
$pure_selectors['active_color'] = "
.active-color,
input[type='text']:focus,
input[type='number']:focus,
input[type='email']:focus,
input[type='search']:focus,
input[type='password']:focus,
input[type='tel']:focus,
textarea:focus,
.button,
button,
input[type='submit'],
.banner.with_mask .before,
.owl-controls .owl-nav .owl-prev:hover,
.owl-controls .owl-nav .owl-next:hover,
.owl-controls .owl-nav .owl-prev:focus,
.owl-controls .owl-nav .owl-next:focus,
.owl-controls .owl-dot.active span,
.breadcrumbs .parent a:hover,
.breadcrumbs .parent a:focus,
.breadcrumbs .current,
.prefooter .shipping-service .icon:hover,
.prefooter .shipping-service .icon i,
.header-wrapper.header-white header.site-header .menu > li > a:hover,
.header-wrapper.header-white header.site-header .menu-main > li > a:hover,
.header-wrapper.header-white header.site-header .menu > li > a:focus,
.header-wrapper.header-white header.site-header .menu-main > li > a:focus,
.header-wrapper.header-dark header.site-header .menu > li > a:hover,
.header-wrapper.header-dark header.site-header .menu-main > li > a:hover,
.header-wrapper.header-dark header.site-header .menu > li > a:focus,
.header-wrapper.header-dark header.site-header .menu-main > li > a:focus,
header.site-header .menu > li > a:hover,
header.site-header .menu-main > li > a:hover,
header.site-header .menu > li > a:focus,
header.site-header .menu-main > li > a:focus,
header.site-header .sub-menu .menu-item a:hover,
header.site-header .sub-menu .menu-item a:focus,
header.site-header .site-search form.focused,
header.site-header .site-search button:hover,
header.site-header .site-search button:focus,
header.site-header .site-search button:active,
.top-bar .menu-item a:hover,
.top-bar .menu-item a:focus,
.top-bar .sub-menu a:hover,
.top-bar .sub-menu a:focus,
.top-bar .cart-quantity:hover,
.top-bar .cart-quantity:focus,
.top-bar .cart-count,
.top-bar .widget_shopping_cart_content .mini_cart_item a:hover,
.top-bar .widget_shopping_cart_content .mini_cart_item a:focus,
.top-bar .widget_shopping_cart_content .mini_cart_item .remove:hover,
.top-bar .widget_shopping_cart_content .total span,
.top-bar.top-bar-white ul.menu:not(.sub-menu) > .menu-item > a:hover,
.top-bar.top-bar-white ul.menu:not(.sub-menu) > .menu-item > a:focus,
.top-bar.top-bar-white .cart-quantity:hover,
.top-bar.top-bar-white .cart-quantity:focus,
.top-bar.top-bar-dark ul.menu:not(.sub-menu) > .menu-item > a:hover,
.top-bar.top-bar-dark ul.menu:not(.sub-menu) > .menu-item > a:focus,
.top-bar.top-bar-dark .cart-quantity:hover,
.top-bar.top-bar-dark .cart-quantity:focus,
header.site-header.fixed .menu .menu-item a:hover,
header.site-header.fixed .menu .menu-item a:focus,
.ps-mobile-menu .menu li a:hover,
.woocommerce-account .woocommerce-MyAccount-navigation li.is-active a,
.team-member:hover .member-image:before,
.contact-form-area form input[type='submit'],
.page .vc_tta-color-grey.vc_tta-style-classic .vc_tta-tab.vc_active > a,
.page .vc_tta-color-grey.vc_tta-style-classic .vc_tta-tab > a:focus,
.vc_tta-color-grey.vc_tta-style-classic .vc_tta-tab > a:hover,
.pagination-wrap .page-numbers li.current a,
.filter-wrap .page-numbers li.current a,
.pagination-wrap .page-numbers li.current span,
.filter-wrap .page-numbers li.current span,
.pagination-wrap .page-numbers li span.current,
.filter-wrap .page-numbers li span.current,
.pagination-wrap .switch-option a:hover,
.filter-wrap .switch-option a:hover,
.pagination-wrap .switch-option.active a,
.filter-wrap .switch-option.active a,
.widget .noUi-horizontal .noUi-handle,
.widget.widget_nav_menu ul.menu a:hover,
.widget.widget_nav_menu ul.menu a:focus,
.widget.widget_mc4wp_form_widget input[type='email']:focus,
.widget.widget_mc4wp_form_widget input[type='text']:focus,
.widget.widget_mc4wp_form_widget input[type='submit'],
.widget.widget_mc4wp_form_widget input[type='button'],
.widget.widget.widget_calendar th,
.widget.widget.widget_calendar a,
.widget.pure_widget_posts .post-meta a:hover,
.widget.pure_widget_posts .post-meta a:focus,
.widget.widget_product_categories ul.product-categories .cat-item a:hover,
.widget.widget_product_categories ul.product-categories .cat-item a:focus,
.widget.widget_product_categories ul.product-categories .cat-item.open .open-this,
.widget.widget_product_categories ul.product-categories .open-this:hover,
.widget.widget_product_categories ul.product-categories > .cat-item > a:hover,
.widget.widget_product_categories ul.product-categories > .cat-item > a:focus,
article.post .entry-description h2 a:hover,
article.post .entry-description h2 a:focus,
article.post a:hover,
#comments .comment-author a:hover,
#comments .comment-author a:focus,
#comments .reply a:hover,
#comments .reply a:focus,
.product-quick-view .mfp-close:hover,
.product-quick-view h1 a:hover,
.product-quick-view h1 a:focus,
.woocommerce-message a:hover,
.woocommerce-info a:hover,
.woocommerce-message a:focus,
.woocommerce-info a:focus,
.quantity span.plus:hover,
.quantity span.minus:hover,
table.cart th.product-remove a:hover,
table.cart th.product-remove a:focus,
.cart_totals .shop_table tbody tr.shipping td span,
.single-product .yith-wcwl-add-to-wishlist a:hover:before,
.product-quick-view .yith-wcwl-add-to-wishlist a:hover:before,
.single-product .compare:hover:before,
.product-quick-view .compare:hover:before,
.single-product .add_to_wishlist:hover:before,
.product-quick-view .add_to_wishlist:hover:before,
.single-product .yith-wcwl-add-to-wishlist a:focus:before,
.product-quick-view .yith-wcwl-add-to-wishlist a:focus:before,
.single-product .compare:focus:before,
.product-quick-view .compare:focus:before,
.single-product .add_to_wishlist:focus:before,
.product-quick-view .add_to_wishlist:focus:before,
.single-product .yith-wcwl-add-to-wishlist a:active:before,
.product-quick-view .yith-wcwl-add-to-wishlist a:active:before,
.single-product .compare:active:before,
.product-quick-view .compare:active:before,
.single-product .add_to_wishlist:active:before,
.product-quick-view .add_to_wishlist:active:before,
.product-quick-view .mfp-close,
.products .onsale,
.products .footer-product .side-button:hover,
.products .footer-product .side-button:focus,
.products .price .woocommerce-Price-amount,
.products .price ins,
.pure-owl-posts .owl-controls .owl-nav .owl-prev:hover,
.pure-owl-posts .owl-controls .owl-nav .owl-next:hover,
.pure-owl-posts .owl-controls .owl-nav .owl-prev:focus,
.pure-owl-posts .owl-controls .owl-nav .owl-next:focus,
.woocommerce #content table.wishlist_table.cart a.remove:hover
";
?>
<?php $active_color = pure_get_redux_option( 'active_color' ); ?>
<style type="text/css">
<?php echo pure_js2tring( $pure_selectors['active_color']); ?>{ color: <?php echo $active_color; ?>; }
</style>
<?php
}
}